### PR TITLE
Add argentina

### PR DESCRIPTION
**Pull request by arielelkin**

### CODE REVIEW

**Comment by lashkhi** [comment]
@arielelkin Hi! Thanks for PR! Could you please specify the city, and please keep the main style? I believe it'll be better to write the name of community and attach link with title "Meetup". So the whole text is in one style.

**Comment by lashkhi** [comment]
@arielelkin Thanks again for changes! Could you please fix the conflicts?- And I'm merging it 🙂

**Comment by arielelkin** [comment]
fixed: https://github.com/lashkhi/iosCommunities/pull/3/commits/90f483bda31ea242a93ff14c9ca0c2ee810a0665

**Comment by lashkhi** [comment]
👍🏻Thanks!

**Pull request merged**
