### PR TITLE
Add San Francisco meetups

### PR DESCRIPTION
**Pull request by rodericj**

### CODE REVIEW

**Comment by lashkhi** [comment]
@rodericj Thanks of PR! Could you please use just name the url as iCal, so it will be something like:
[iCal](https://calendar.google.com/calendar/ical/ho60q57pauegr2ki4v9hhspvdo%40group.calendar.google.com/public/basic.ics) 
*Copy and paste this into your calendar's "subscription" functionality rather than downloading the static file.

**Comment by rodericj** [comment]
@lashkhi the issue with that is then people would be able to click on it which would download the static version which is undesirable. Thoughts?

**Comment by lashkhi** [comment]
@rodericj  Well, you still leave the description:
*Copy and paste this into your calendar's "subscription" functionality rather than downloading the static file.

**Comment by rodericj** [comment]
I'm down to change it so the link resolves, but literally 0 people will do it correctly if they actually click the link and their data will be incorrect.

**Comment by lashkhi** [comment]
@rodericj  ok, lets leave a link as it was at the beginning. Could you please resolve the conflicts so I could merge it?🙂

**Comment by rodericj** [comment]
Moved to a new PR here: #17

**Comment by rodericj** [comment]
Thanks for your patience!

**Pull request closed without merging**
